### ISSUE TITLE
I got the wrong result

### ISSUE THREAD

**Issue by SongYii** [luiszeni/Boosted-OICR#1]
Hello,  I am very interested in your work. But I didn't get the correct result. The map on the trainval is basically 0. I don’t know what went wrong, but I can got the correct result using the pre-trained weights you provide. Does your last submission fix this problem?

~~~~~~~~~~~~~~~~~~~~
Final mAP Results:
0.0, 9.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5

**Comment by luiszeni** [comment]
Hi, Yeah it is a known bug,  I believe that I made some mistake when I was preparing the code to release. 

Yesterday I released a commit that I hope solves this issue.

**Comment by SongYii** [comment]
I will try again today, thank you very much for your reply

**Comment by luiszeni** [comment]
Nice, probably I will make some adjustments in the code next two weeks.
However, feedback is welcome.
