### ISSUE TITLE
Multi-GPU Training Support?

### ISSUE THREAD

**Issue by Markin-Wang** [luiszeni/Boosted-OICR#10]
Hi, I am interested in your work and thanks for your code.
I wonder whether the code support the multi-gpu training?

Best Regards,
Jun

**Comment by luiszeni** [comment]
Hi, the code has no multi-gpu support. 

I have only a single-gpu machine to work on, so it makes no sense to support such a feature in my code :).

**Comment by Markin-Wang** [comment]
> Hi, the code has no multi-gpu support.
> 
> I have only a single-gpu machine to work on, so it makes no sense to support such a feature in my code :).

I found there are many multi-gpu settings both in the source codes and configuratoin file, so I posted this issue.
Thanks again for your early reply and help.
