### ISSUE TITLE
how to test on the pascal voc 2012 test?

### ISSUE THREAD

**Issue by Horatio-Ng** [luiszeni/Boosted-OICR#14]
hi, could you please tell me how to test on the pascal voc 2012 test?

**Comment by luiszeni** [comment]
Hi, sorry about the delay. 

1- You need to run the testing script on test set of PascalVOC 2012.
2-You can find each class .txt detections file on the folder /Boosted-OICR/snapshots/oicr_lambda_log_distillation/<a date time val>/test/model_step24999/...
3- Now you can use the instructions in the Pascal Voc server to create a .zip package with these .txts.
4- Send it.
5- Wait for a long time.

Hope it helps.
