### ISSUE TITLE
Reasons for non-reproducibility

### ISSUE THREAD

**Issue by Markin-Wang** [luiszeni/Boosted-OICR#15]
Hi, thanks for your work again.
Your previous version of code can not achieve the mAP you claimed, but your current version reached.
I guess the main reason for this difference is due to the different ways to process VOC2007 annotations.
Note that the evaluation of VOC2007 object challege excluedes the object marked difficult and this can be found in their  [paper](https://homepages.inf.ed.ac.uk/ckiw/postscript/ijcv_voc09.pdf).

In your current version, you used the coco format annotation and code, which excludes the object marked difficult (see ignore attribute in json files and __add_gt_annotations function in json_dataset.py), while in your previous version (well organized one), you directly processed the annotation file and parsed the annotation file, and hence did not ignore the difficult objects.  

In your current version, I annotated the code about ignoring the difficult objects and reran the code. A 47 mAP was achieved which is similar to your previous code.
I am not sure you can achieve the mAP reported in your paper after you modifiying the code in your well-organized version, but I think this is a big improvement and look forward to your well-organized version.

**Comment by luiszeni** [comment]
Hi, good point!  I forgot about the dificult guys. :facepalm:

I think that there are more problems in the refactored code and because that you where not able to reproduce the results. 

Thanks :)
