### ISSUE TITLE
Batch size discrepency

### ISSUE THREAD

**Issue by bradezard131** [luiszeni/Boosted-OICR#4]
Hey,

Your paper states a batch size of 2, however it appears in the code/configs that you are accumulating gradients over 4 iterations (i.e. effective batch size of 8, just split up to fit in GPU memory). Can you please confirm whether this is an error in the paper or the repository?

**Comment by luiszeni** [comment]
Hi, the value informed in the paper is wrong.  Thanks to point it out :).  If I remember right, in the code we are accumulating gradients of 4 images, meaning the bach size used is 4.
