### ISSUE TITLE
octave problem

### ISSUE THREAD

**Issue by hust-huangjunhe** [luiszeni/Boosted-OICR#9]
![图片](https://user-images.githubusercontent.com/44351172/91243394-81ed6080-e77c-11ea-845f-01f19ad0026d.png)
Hi,when I use the pretrained model to test the voc2007test dataset,It occured this problem.And I don't know how to fix it,can you help me?Thanks!

**Comment by luiszeni** [comment]
Hum, I made no testing using windows OS. Seems that something really strange is happening when your python try to call the octave.  I have no experience running external binaries using python on windows and I have no plan making my code  to work on windows. 

My best sugestion is: Change to linux bro =)

... Anyway, a starting point could be running the  "octave --eval voc_eval(...)" command directilly on your windows terminal and see if it works externally from python.  If it is working you need to find a way to fix the call from python.

**Comment by hust-huangjunhe** [comment]
Thank you very much!It seems that I should install octave in my windows OS.But I will run the code in Linux server,so I change to the linux server to run the code.When I run the 'test.py',It also occured the octave problem.Is it because I didn't install octave in linux server?Thanks again!
![图片](https://user-images.githubusercontent.com/44351172/91387998-0e754d00-e869-11ea-9e43-1bebd3127699.png)

**Comment by luiszeni** [comment]
yes, octave is a requirement. I did not put this requirement on the readme, shame on me, I just updated it there with it.
